Redesign/103 post creation page re design
keep-starknet-strange/joyboy pull request #112
Opened 2024-05-27 12:38 UTC by josephchimebuka

I redesigned the post creation page. Addressing the issue #108

2024-05-27 12:46 UTC, ugur-eren commented on JoyboyCommunity/src/modules/post/index.tsx
> +      </IconContainer>
can you fix the formatting for this part? running `yarn format` will automatically fix the formatting issues

2024-05-27 12:47 UTC, ugur-eren commented on JoyboyCommunity/src/modules/post/styled.ts
> +  display: flex;
Please remove the duplicates

2024-05-27 12:49 UTC, ugur-eren commented on JoyboyCommunity/src/modules/post/styled.ts
> +    margin-left: 10;
There is no unit on margin-left

2024-05-27 12:50 UTC, ugur-eren requested changes
I've requested some changes. Also icons should not be png's, it should be svg. You can extract svg from the figma file, and you can use it by creating an icons folder in the assets. You can use svgr to convert svg's into react native svg.

2024-05-28 08:59 UTC, josephchimebuka commented
Applied all the changes and formatted the code as well

2024-05-28 09:05 UTC, ugur-eren commented on JoyboyCommunity/src/modules/post/index.tsx
>        </Container>
PostButton doesn't have a closing tag

2024-05-28 09:06 UTC, ugur-eren commented on JoyboyCommunity/assets/svgs/svgComponents/Gif.tsx
> +function GifIcon(props) {
For every svg, can we have typescript types too? For example:
```tsx
export const GifIcon: React.FC<SvgProps> = (props) => {
  ...
}
```

2024-05-28 13:58 UTC, josephchimebuka commented
I have removed the unused components and images

2024-05-28 14:39 UTC, merged