Auth screens UI
keep-starknet-strange/joyboy pull request #114
Opened 2024-05-27 14:00 UTC by princeibs

Closes #92

2024-05-31 10:14 UTC, ugur-eren commented on JoyboyCommunity/assets/svgs/svgComponents/DoubleCopy.tsx
> +  <Svg width={24} height={24} fill="none" {...props} viewBox="0 0 24 24">
Icons moved to the [icons.tsx](https://github.com/keep-starknet-strange/joyboy/blob/be01de1509e512a128715d04cfc5b90beee49fc1/JoyboyCommunity/src/assets/icons.tsx) file, can you move the icons to there?

2024-05-31 10:15 UTC, ugur-eren commented on JoyboyCommunity/assets/svgs/svgComponents/Info.tsx
> +      clip-rule="evenodd"
Svg attributes should be camelCased, for example `fill-rule` should be `fillRule`

2024-05-31 10:17 UTC, ugur-eren requested changes
Hi, I've requested some changes regarding the SVGs. Other than that looks great! Thank you for the work.

2024-06-02 07:28 UTC, princeibs commented
All issues resolved ✅
@ugur-eren

2024-06-02 08:34 UTC, ugur-eren approved these changes
Thanks for the great work! LGTM

2024-06-02 08:34 UTC, merged