feat(frontend): implement tip screen design
keep-starknet-strange/joyboy pull request #176
Opened 2024-06-16 14:18 UTC by kateberryd

2024-06-16 17:02 UTC, ugur-eren requested changes
Thanks for the work! I've requested some changes. There are a lot requests but most of them are the same request

2024-06-16 17:02 UTC, ugur-eren commented on JoyboyCommunity/src/modules/Tip/styles.ts
> +    height: 728,
Height should not be constant

2024-06-16 17:02 UTC, ugur-eren commented on JoyboyCommunity/src/modules/Tip/styles.ts
> +  innerPostHeader: {flexDirection: 'row', gap: 5, alignItems: 'center'},
Styles should not be single lines

2024-06-16 17:02 UTC, ugur-eren commented on JoyboyCommunity/src/modules/Tip/styles.ts
> +    backgroundColor: '#EC796B1A',
This color already defined in the theme if im not wrong, it should be primaryLight

2024-06-17 12:26 UTC, ugur-eren requested changes
Thanks for the work! Only small details remaining, like moving inline styles to styles.ts file and using theme colors from useTheme hook. After that we can merge it.

2024-06-17 12:26 UTC, ugur-eren commented on JoyboyCommunity/src/modules/Tip/index.tsx
> +              />
You can use Avatar component, it provides polygon effect, and you can pass the size as `<Avatar size={48} />` directly.

2024-06-17 12:26 UTC, ugur-eren commented on JoyboyCommunity/src/modules/Tip/index.tsx
> +          <View style={{marginBottom: 20}}>
There shouldn't be inline styles, these should be moved to the styles.ts file

2024-06-17 16:00 UTC, ugur-eren approved these changes
Thanks for the work! looks great

2024-06-17 16:00 UTC, merged

2024-06-17 16:07 UTC, kateberryd commented
Thank you @ugur-eren