event escrow for deposit claim and cancel
keep-starknet-strange/joyboy pull request #184
Opened 2024-06-18 13:41 UTC by MSghais

Add Events on Escrow for: 

- Deposit
- Claim
- Cancel

2024-06-18 14:32 UTC, maciejka requested changes

2024-06-18 14:32 UTC, maciejka commented on onchain/src/social/deposit.cairo
> +    #[key]
Add deposit_id, indexed.

2024-06-18 14:32 UTC, maciejka commented on onchain/src/social/deposit.cairo
> +struct DepositEvent {
Add deposit_id, indexed.

2024-06-18 14:32 UTC, maciejka commented on onchain/src/social/deposit.cairo
> +struct CancelEvent {
Add deposit_id, indexed.

2024-06-18 14:32 UTC, maciejka commented on onchain/src/social/deposit.cairo
> +    enum Event {
There should be a TransferEvent in case escrow is not necessary.

2024-06-18 14:32 UTC, maciejka commented on onchain/src/social/deposit.cairo
> +            self.emit(CancelEvent { sender:get_caller_address(), recipient:deposit.recipient, amount:deposit.amount, token_address:deposit.token_address });
Move event to the end of the function.

2024-06-18 14:32 UTC, maciejka commented on onchain/src/social/deposit.cairo
> +            self.emit(ClaimEvent { sender:get_caller_address(), recipient:request.public_key, amount:deposit.amount, token_address:deposit.token_address });
Same as above.

2024-06-19 07:54 UTC, ugur-eren commented
Hi @MSghais  @maciejka is it possible to have an event for deposit transfers too? For this part:

```rust
if (!recipient.is_zero()) {
    let erc20 = IERC20Dispatcher { contract_address: token_address };
    erc20.transfer_from(get_caller_address(), recipient, amount);
    return DepositResult::Transfer(recipient);
}
```

2024-06-19 09:12 UTC, maciejka requested changes

2024-06-19 09:12 UTC, maciejka commented on onchain/src/social/deposit.cairo
> +        TransferEvent: TransferEvent,
TransferEvent should be emited around line 153

2024-06-19 09:12 UTC, maciejka commented on onchain/src/social/deposit.cairo
> +    sender: ContractAddress,
Sender should be indexed, add [key].

2024-06-19 09:12 UTC, maciejka commented on onchain/src/social/deposit.cairo
> +    recipient: NostrPublicKey,
Recipient should be indexed, add [key].

2024-06-19 09:12 UTC, maciejka commented on onchain/src/social/deposit.cairo
> +    sender: ContractAddress,
Sender should be indexed, add [key].

2024-06-19 09:12 UTC, maciejka commented on onchain/src/social/deposit.cairo
> +    recipient: NostrPublicKey,
REcipient should be indexed, add [key].

2024-06-19 09:12 UTC, maciejka commented on onchain/src/social/deposit.cairo
> +    sender: ContractAddress,
Sender should be indexed, add [key].

2024-06-19 09:12 UTC, maciejka commented on onchain/src/social/deposit.cairo
> +    recipient: NostrPublicKey,
Recipient should be indexed, add [key].

2024-06-19 09:12 UTC, maciejka commented on onchain/src/social/deposit.cairo
> +                        deposit_id: deposit_id + 1,
Why `deposit_id + 1`?

2024-06-19 09:12 UTC, maciejka commented on onchain/src/social/deposit.cairo
> +struct ClaimEvent {
Events can be moved inside of `mod DepositEscrow`.

2024-06-19 09:13 UTC, maciejka commented
> Hi @MSghais @maciejka is it possible to have an event for deposit transfers too? For this part:
> 
> ```rust
> if (!recipient.is_zero()) {
>     let erc20 = IERC20Dispatcher { contract_address: token_address };
>     erc20.transfer_from(get_caller_address(), recipient, amount);
>     return DepositResult::Transfer(recipient);
> }
> ```

You are right, added in the comments.

2024-06-19 12:39 UTC, maciejka requested changes

2024-06-19 12:39 UTC, maciejka commented on onchain/src/social/deposit.cairo
> +                        deposit_id: deposit_id,
Use `deposit_id` instead of  `deposit_id: deposit_id`, here and below.

2024-06-19 12:42 UTC, maciejka requested changes

2024-06-19 12:42 UTC, maciejka commented on onchain/src/social/deposit.cairo
> +        recipient: NostrPublicKey,
Starknet address of the recipient is missing here.

2024-06-19 12:42 UTC, maciejka commented on onchain/src/social/deposit.cairo
> +        recipient: NostrPublicKey,
Starknet address of the recipient is missing here as well

2024-06-19 12:42 UTC, maciejka commented on onchain/src/social/deposit.cairo
> +                            recipient: recipient,
types do not match

2024-06-20 09:09 UTC, maciejka requested changes

2024-06-20 09:09 UTC, maciejka commented on onchain/src/social/deposit.cairo
> +        recipient: NostrPublicKey,
Let's change it to `nostr_recipient`.

2024-06-20 09:09 UTC, maciejka commented on onchain/src/social/deposit.cairo
> +        recipient: NostrPublicKey,
`nostr_recipient`

2024-06-20 09:09 UTC, maciejka commented on onchain/src/social/deposit.cairo
> +        recipient: NostrPublicKey,
`nostr_recipient`

2024-06-20 09:09 UTC, maciejka commented on onchain/src/social/deposit.cairo
> +        starknet_recipient: ContractAddress,
There is no `starknet_recipient` for `CancelEvent`.

2024-06-20 14:48 UTC, maciejka approved these changes

2024-06-20 14:48 UTC, merged